# @package _global_          
# merge this file to global config

dataset:
  task: seg

model:
  num_classes: 2

training:
  data:
    transforms:
      normalize: true
      image_size: [3, 256, 256]
      
evaluation:
  per_class: true
  class_names: 
    - OD
    - OC